### PR TITLE
improve desk reject actions

### PR DESCRIPTION
**Pull request by melisabok**
- remove unnecessary code from the desk reject process function
- remove get original note
- move the track map to its own file so it can be imported by other files.

### CODE REVIEW

**Comment by celestemartinez** [comment]
I added the paper title to the email subject as Rodrigo pointed out during the meeting that authors don't know their paper numbers and using the title will help them identify their papers.

**Review by celestemartinez — APPROVED** [review]

**Comment by melisabok** [comment]
Cool! you mean the SAC don't know their paper numbers...

**Comment by celestemartinez** [comment]
I meant authors! I see now that we are not sending an email to authors but PCs want us to, so authors know if their paper is desk-rejected

**Comment by melisabok** [comment]
More updates:

- refactor to build the SAC track id
- add the conflict group as nonreaders of all the notes
- fix signature for comments
- use tqdm to check the progress

**Comment by celestemartinez** [comment]
Added:

- a preprocess function for suggested decision invitations which forces SACs to input a ranking if they select 2 or 3 in suggested decision

**Comment by melisabok** [comment]
Thanks for the changes!

**Pull request merged**
